### ISSUE TITLE
Get the namespace at runtime for the core init scrips 

### ISSUE THREAD

**Issue by eastlondoner** [neo4j-contrib/neo4j-helm#104]
Currently we use the namespace at template-creation time to modify the startup script of the core statefulsets and set the discovery advertised address.

You can get the namespace at runtime using `cat /var/run/secrets/kubernetes.io/serviceaccount/namespace`

This line in the core startup command could be changed to make use of this:

```
export DISCOVERY_HOST="discovery-{{ template "neo4j.fullname" . }}-${core_idx}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
```

**Comment by moxious** [comment]
what's the advantage of doing it this way?

At helm install time, the namespace must always be specified and known, so what's the utility of doing it later?  Is there a use case in here about people wanting to take an existing helm install and somehow move it / port it to a different namespace?  (Because this would enable that, but I'm interested to know more about if that's possible or why you'd want to do it)

**Comment by eastlondoner** [comment]
This came up with users who didn't have/were not permitted to use helm. 
They used helm to generate templates but didn't know the namespace they were going to actually use. 

I think this is the only place where the namespace gets written into the actual _yaml_

**Comment by moxious** [comment]
that makes sense, and in that case it should be OK.   It's desirable for other reasons to use helm just as a templating engine and not have it actually manage releases, so if that's what we're accomplishing here that's workable

**Comment by eastlondoner** [comment]
it's worth thinking about - I am not at all convinced that my proposed solution is an improvement.
