### ISSUE TITLE
Community version

### ISSUE THREAD

**Issue by robsonpeixoto** [neo4j-contrib/neo4j-helm#117]
Are there plan to add community version support ?

**Comment by moxious** [comment]
Not at the moment.  I can recommend a few things though.

* Community supports standalone only, so if you set core.standalone=true and imageTag=4.1.2 (instead of 4.1.2-enterprise which is the default) it might already work, you should give it a shot
* Neo4j offers a number of commercial licensing options, outlined above: both paid and free, including free licenses for development, startup, and academic-educational uses and of course evaluation.  See: https://neo4j.com/licensing/

**Comment by moxious** [comment]
I suspect that pretty minimal changes would be needed to make community work in standalone only mode; open to PRs

**Comment by bbenzikry** [comment]
@robsonpeixoto We started out with the community version and used the chart with the community version image in standalone mode as @moxious suggested and did not experience any issues.

**Comment by robsonpeixoto** [comment]
Is required set `acceptLicenseAgreement=yes` using the community edition?

**Comment by moxious** [comment]
@robsonpeixoto I don't believe that this setting is required for community, but it also hurts nothing if it stays; I think (if memory is right) that it just gets ignored.  The license agreement for community is GPLv3 and doesn't require explicit acknowledgment.

**Comment by moxious** [comment]
Is there anything further on this issue or can it be closed?  Did you run into any trouble running community in this way?

**Comment by robsonpeixoto** [comment]
It's working for me. Thanks!
