### ISSUE TITLE
leader election

### ISSUE THREAD

**Issue by srfaytkn** [neo4j-contrib/neo4j-helm#125]
When I deleted the leader pod while testing the neo4j, the writing requests failed and the leader did not change. 

<img width="858" alt="pods" src="https://user-images.githubusercontent.com/19591219/97290079-1fd2d980-1859-11eb-870f-bd8ddcae355d.png">

![sysinfo](https://user-images.githubusercontent.com/19591219/97290052-16e20800-1859-11eb-94f1-5828ad44401a.png)

**Comment by moxious** [comment]
In 4.0, leadership is database specific.  That means at a minimum, you have *2* leaders.  1 for system db, the other for the default db (usually neo4j).

I can't tell from the output here what's happening.  It's possible that if you kill *a* leader, when it comes back the cluster could elect it leader of something (not necessarily the same database).    This gets more complicated if you have a multidb setup, because it's entirely possible that all 3 machines are leaders of something.

So I'm not sure what to make of this.

The debug.log file that gets generated by Neo4j will always have a log of when leadership elections happen, terms, and who won and so forth.  So that's the place to look if you're wondering what the cluster is saying to itself and what it thinks the internal state of leadership is.

**Comment by srfaytkn** [comment]
thanks for helping,  i found the leader change from logs but i couldn't understand why it has been elected as the leader before core-0 was ready

**Comment by moxious** [comment]
In a 3-member cluster, you only need a majority to elect a leader.  So even if core-0 isn't ready, core-1 and core-2 are a majority of the minimum cluster size (3) so they can make a decision without involving core-0.  That's necessary since there are failure scenarios where core-0 goes offline and does not come back.

More docs here: https://neo4j.com/docs/operations-manual/current/clustering-advanced/lifecycle/#causal-clustering-transacting-via-raft-protocol

**Comment by srfaytkn** [comment]
Thanks for help
