### ISSUE TITLE
AWS backup/restore creds come from environment instead of file

### ISSUE THREAD

**Issue by gwvandesteeg** [neo4j-contrib/neo4j-helm#129]
Issue:

Don't rely on the credentials to be provided via the credentials file

Reasoning:

The AWS credentials currently require the credentials file but could also come from:
* the environment variables, either specified or injected from a Secret (similar to the credentials file)

But if the cluster is run on AWS they can also be granted the access from:
* the underlying worker node's IAM instance profile
* kube2iam controller

Workaround:
* specify an empty file or one with only the region specified

**Comment by moxious** [comment]
If you would use kube2iam controller or the underlying worker node's IAM instance profile, would the aws cli inside of a container just be expected to magically work without an auth step?

If that's the case, then we would at least need a separate flag to be provided to the container indicating that IAM is provided for by the outer environment, so that the activate_aws function in backup.sh does not need to be called.  What would you suggest?

**Comment by gwvandesteeg** [comment]
Correct,

The only thing you might need to set would be the AWS region, the rest doesn't require the auth step.  It can be solved here i think with just some additional documentation. If the user just sticks an empty credentials file in, the script will handle it fine and the aws CLI tool automatically deals with getting the right credentials from wherever it needs to.

**Comment by moxious** [comment]
I'm happy to add this to the docs, but to be honest I don't know much about the underlying methods that you're suggesting can be used for auth.   Can you suggest a paragraph describing what you're after?  I'll do a PR for it and some editing to put it into the right place, I just need more precision on what you're suggesting.

The work-around (where you have a trivial file that indicates region only) I think is better & cleaner than trying to make the credentials file completely optional, since switching on different methods of doing authentication within the script will tend to complicate things.

**Comment by jtyr** [comment]
I would also like to use [GKE Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) or [AWS STS](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html) instead of using static credentials. It's much more secure and flexible. It requires the following:

1) Configure your Kubernetes cluster to support this method of authentication.
2) Create cloud identity with permissions to specific cloud resources (IAM Role in AWS;  Service Account + IAM Role in GCP).
3) Create Kubernetes Service Account with a specific `annotation` which links it to the cloud identity.
4) Run your pod with that Kubernetes Service Account.

Once the container is running, you should have direct access to the cloud resources you permitted in the IAM Role. Tools like `aws` and `gcloud`/`gsutil` usually work out of the box. Other tools might need a little help by extract tokens from files inside the container (AWS) or from the meta server (GCP).

**Comment by moxious** [comment]
Closed via merged PR here https://github.com/neo4j-contrib/neo4j-helm/pull/137
