### ISSUE TITLE
Bootstrapping operations for neo4j containers

### ISSUE THREAD

**Issue by salehio** [neo4j-contrib/neo4j-helm#145]
What is the recommended way for performing bootstrapping operations on the neo4j containers via config?

For example, I believe my SSL configuration is failing due to lack of trusted/ and revoked/ directories, and would like to add them via a `mkdir` or something. Does the helm expose such a way to do this? And if not, how is it expected we create those directories?

**Comment by moxious** [comment]
The recommended way of doing this is with an initContainer.  In general, if you need to prepare a docker container's environment, that's the way to go.  Have a look into how the restore container works (it's documented) because it runs as an initContainer and provides an example of how to mount the right volumes and so on.  Once you're inside of an initContainer, you can use any shell script you like to prepare directories as you choose.

**Comment by salehio** [comment]
Thanks! Out of curiosity, are there any other ways to achieve this?

**Comment by moxious** [comment]
Off of the top of my head there are alternatives:

- You can pre-allocate PVCs under the right names which your helm install will need; you can then pre-prepare these volumes however you wish with separate containers so that when your neo4j pods "claim" the volumes, they're already nicely done.

- You can mount a configMap as a volume in Kubernetes.  So you don't have a disk at all, or ever create a directory -- rather simply specify all of your trusted key stuff in a set of configmaps mounted to the right places with additional volumes.

- You could modify the helm chart itself and look into the pod init script (right here: https://github.com/neo4j-contrib/neo4j-helm/blob/master/templates/pod-init-script.yaml#L14) and modify that -- it's already bash that executes whenever your containers start.

But honestly the cleanest and simplest option (in my opinion) is either initContainers or config maps.

**Comment by salehio** [comment]
Thanks again for your help. <3
