### ISSUE TITLE
randomized password breaks on upgrade

### ISSUE THREAD

**Issue by kraney** [neo4j-contrib/neo4j-helm#146]
If a password is not set but auth is on, a random password is generated, which is great - on initial install. The problem is, on `helm upgrade` it is re-randomized, but the password setting in the database is not updated. So everything is borked from that point forward.

**Comment by kraney** [comment]
There's a potential workaround for this described here:
https://github.com/helm/charts/issues/5167#issuecomment-641558251

**Comment by moxious** [comment]
This isn't a password break; documented with the neo4j product is that you only get to set the initial password once.   Passwords and such are stored in the system database, and so when you "helm upgrade" no new password can be set because you already have a system database.  The whole "initial password" thing only works when you don't have existing data on disk in a system database.

To dynamically _reset_ the password is not going to be possible from helm, because in order to reset the password, we must either delete the system database, or else let the neo4j service come live so that we can use regular cypher to do so.   After first initialization, users need to note the password and make explicit changes with Neo4j functions after that.

Perhaps this issue though is that the chart needs to detect "upgrade" actions, and then refuse to do anything related to the password in that scenario.  It can't work, and so shouldn't be there.

**Comment by kraney** [comment]
Yes, the latter. I don’t care that the password can’t be changed, I care that the stored working one gets obliterated with a new one that cannot possibly work. And the comment I linked above provides a formula for doing just that in the secret.yaml template where the password is generated.

**Comment by moxious** [comment]
Linked PR https://github.com/neo4j-contrib/neo4j-helm/pull/148
