### ISSUE TITLE
Can't start a cluser with two cores

### ISSUE THREAD

**Issue by lpanichi** [neo4j-contrib/neo4j-helm#152]
I ran the following :
```
helm install mygraph https://github.com/neo4j-contrib/neo4j-helm/releases/download/4.2.0-1/neo4j-4.2.0-1.tgz \
    --set acceptLicenseAgreement=yes \
    --set neo4jPassword=kubernetes \
    --set core.numberOfServers=2 \
    --set readReplica.numberOfServers=0 \
    --set core.persistentVolume.enabled=false \
    --set readinessProbe.initialDelaySeconds=1200 \
    --set livenessProbe.initialDelaySeconds=1200
```
And the logs are
```
2020-12-26 19:16:08.604+0000 INFO  Database 'system' is waiting for a total of 3 core members...
```

The point is, I'm in a local test environment and I prefer to run only two cores.
Did I miss a configuration ?

I looked into the helm chart and there is this line :
```
default_label_selector="neo4j.com/cluster={{ template "neo4j.fullname" . }},neo4j.com/role=CORE,neo4j.com/coreindex in (0, 1, 2)"
```
So I'm guessing here is the problem ?
Besides, what will happen when I will run a cluster with 4 cores ? The core number 3 will never be discovered ?

**Comment by moxious** [comment]
Please have a look at the causal cluster architecture on Neo4j's site.   https://neo4j.com/docs/operations-manual/current/clustering/introduction/#causal-clustering-introduction

Starting a cluster with 2 members is not a sensible thing to do period, because of the way Neo4j's architecture works.  As a result of that, inside the helm chart we configure (in cluster mode) that clusters must form with a minimum set of 3.  And so this isn't something that we can support with this chart.
