### ISSUE TITLE
Helm installation failed when logging in with neo4jPassword

### ISSUE THREAD

**Issue by flavioab** [neo4j-contrib/neo4j-helm#154]
**Describe the bug**

When setting `neo4jPassword` value using the helm chart it is impossible to login via neo4j-browser or using `./bin/cypher-shell` with username *neo4j* and set password both return the following message:

```
Neo.ClientError.Security.Unauthorized: The client is unauthorized due to authentication failure
```

Same happens when not setting `neo4jPassword` and leaving the option `authEnabled: true`.

Only possible configuration that I managed to make it work was setting `authEnabled: false` and logging with the default user password. `neo4j/neo4j`.

**To Reproduce**
1. Install with `authEnabled: true` and set or not `neo4jPassword`
2. Go to browser ui and try to login or try via cli using `./bin/cypher-shell`

**Expected behavior**
Login happens with success.

**Error Logs**

```
Neo.ClientError.Security.Unauthorized: The client is unauthorized due to authentication failure
```

**Additional context**

Helm chart version: 4.2.0-1
Neo4j version: 4.2.0-1

**Comment by moxious** [comment]
I cannot reproduce this behavior.  But I know it's possible, when PVCs are reused.

Have you uninstalled and reinstalled the cluster under the same name, possibly more than once?

When you uninstall neo4j from helm, it does not remove the underlying PVCs, which contain Neo4j's system database, which contains the *initial* password you set *on first install*.  Subsequent installs reuse the same PVCs, and the "initial password" feature doesn't work, because you're inheriting the old password from the previous install.

Can you confirm whether this is the case?

**Comment by moxious** [comment]
Troubleshooting reference to the docs that discuss this: https://neo4j.com/labs/neo4j-helm/1.0.0/troubleshooting/#_i_specified_a_password_on_install_and_it_didnt_work

**Comment by moxious** [comment]
Is this related?  https://github.com/neo4j-contrib/neo4j-helm/issues/158

**Comment by flavioab** [comment]
Hi @moxious it is related to #158 , thanks a lot for answering! Gonna try the new release and see if this works for me, seems like a simple fix.

Closing it for now
