### ISSUE TITLE
Prometheus Metrics Endpoint

### ISSUE THREAD

**Issue by srfaytkn** [neo4j-contrib/neo4j-helm#169]
When I send a request to localhost: 2004 inside neo4j container, the metrics are available, but when I request from outside the container with the ip address, it returns error.

**To Reproduce**
1. connect neo4j container terminal
2. curl localhost:2004
3. it returns metrics
4. create new simple pod
5. connect pod terminal
6. curl x.x.x.x:2004(neo4j container ip adress) then it returns 'Connection refused'

**Expected behavior**
return of prometheus metrics

**Comment by eastlondoner** [comment]
@srfaytkn the Prometheus endpoints are published on the "discovery" service for each core. Can you try fetching them using the discovery service dns name?

**Comment by srfaytkn** [comment]
i tried and same result
```
curl http://discovery-neo4j-single-neo4j-0.neo4j.svc.cluster.local:2004
Failed to connect to discovery-neo4j-single-neo4j-0.neo4j.svc.cluster.local port 2004: Connection refused
```

**Comment by eastlondoner** [comment]
Ok then this sounds like a bug.

I suspect that the Prometheus endpoint config setting isn't set correctly:

https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_metrics.prometheus.endpoint

You can try changing that setting - but it may not be the cause of the problem, that's just a guess.

I will probably not be able to investigate further until this evening

**Comment by eastlondoner** [comment]
@srfaytkn it turns out that the necessary configuration is exposed to the helm yaml but the default value and the documentation both use `localhost` that limits access to prometheus as you have found. Using `0.0.0.0` instead makes prometheus available on all network interfaces.

If you set this in your values.yaml: 

```
metrics:
  prometheus:
    enabled: true
    endpoint: "0.0.0.0:2004"
```

Then you should be able to access prometheus from outside the neo4j container.

I have made a PR to improve the documentation: https://github.com/neo4j-contrib/neo4j-helm/pull/170

I will think about whether we can change the default value of that parameter safely.

**Comment by srfaytkn** [comment]
@eastlondoner thanks, it worked for me

**Comment by darshan4Asp** [comment]
@eastlondoner @srfaytkn 
It's not working for me.. If i change endpoint to 0.0.0.0:2004 in neo4j.conf file then neo4j container is not started. and there are some errors. with endpoint localhost:2004 , getting error as per below in agent. 
| WARN  | unable to collect metrics error="unable to perform request: Get \"[http://localhost:2004/metrics\":](http://localhost:2004/metrics/%22:) read tcp 127.0.0.1:43008->127.0.0.1:2004: read: connecti>
