### ISSUE TITLE
Provide single core resources

### ISSUE THREAD

**Issue by sdaschner** [neo4j-contrib/neo4j-helm#20]
For simpler setups it might already be helpful to deploy a standalone, single core instance of Neo4J, but with the full manageability, i.e. persistent volumes, backup jobs, etc.

I've forked the chart and removed all services and discovery settings that are not required in single mode into the following branch: https://github.com/sdaschner/neo4j-helm/tree/single-instance

I also wrote the following post that aims to explain what's required step-by-step: https://blog.sebastian-daschner.com/entries/neo4j-single-core-managed-k8s

WDYT? Happy to provide a PR to a seperate branch / directory or else, if you think that might be helpful for more folks (I've used that example in a real-world project, btw.).

**Comment by gugacavalieri** [comment]
Good one @sdaschner ! I will be using your implementation since we will be deploying Neo4J in K8s for our staging env :)

Maybe it would be a good idea to have a separated branch for that in the official repository!

**Comment by moxious** [comment]
@sdaschner first -- I really want to thank you for doing this along with the blog post and video.  I looked through the code this morning and I see how you did it.

No question in my mind it's useful to have some form of contribution that lets this chart run as a stand-alone instance.

I probably couldn't accept a PR on the basis of the forked code because the fork wasn't adding a feature but rather more stripping all of the clustering bits out.  The main question in my mind is how best to set it up so that it could work either way.

One option would be to have a value passed (something like standalone=true) in which case you'd get basically the same as what you did in your chart.   The other way would be to explain in the docs that if number of core servers is set to 1, that's effectively what you'll get.   Both make sense in different ways.

Both have the requirement though to do a bit more validation.  So for example, cores=1 and read replicas=2 doesn't make any sense and can't be legal/valid.  

What I'm considering right now (feedback welcome)

- Add a [helm schema](https://helm.sh/docs/topics/charts/#schema-files) to provide for tighter validation of what values are allowed to be passed to the chart
- Add a parameter standalone=true/false (default false).
- Disallow the use of any `core.*` and/or `readReplica.*`, if standalone=true.
- Otherwise, all other config would work identically.   In a stand-alone scenario, you'd probably still have a statefulset with 1 member.

A major alternative would be to have a separate helm chart for standalone, rather than trying to combine them and get fancy with options.  Personally, I really don't like this option because time is limited, and the number of operational features that need to be built into these helm charts would make keeping them in sync / porting changes likely a constant pain.   But I'm open to counter-arguments.

**Comment by moxious** [comment]
Oh, and additionally -- we'd have to add a single instance standup to the CI build system to verify that this works going forward, but that's not too big of a deal.

**Comment by sdaschner** [comment]
@moxious Thanks for your kind words :) And yes, fully agree that a simple PR doesn't make sense, hence this issue first.

I fully +1 your considerations. I was thinking about a more implicit version, if `core.numberOfServers` is `1`, since any value less than `3` doesn't work otherwise anyway, but I think your suggestion is more explicit to the user, since the mode of operation will also differ, so I agree.

Also +1 with keeping a single Helm chart that's up to date.

Please let me know if there's anything I can help with.

**Comment by moxious** [comment]
I asked a few other Neo4j internal folks and got some general head-nodding, so I'll look into doing this on a branch and see how far I can get.

**Comment by moxious** [comment]
WIP: https://github.com/neo4j-contrib/neo4j-helm/pull/21/files

**Comment by moxious** [comment]
Single-core is merged onto the master branch at this point.   But I'll defer closing the issue until we have a release pressed that includes it.   I'm working on backup/restore, which once that's in, we'll cut a release.

**Comment by moxious** [comment]
Closed by release https://github.com/neo4j-contrib/neo4j-helm/releases/tag/4.0.5-1
