### ISSUE TITLE
Issue when setting apoc export or import configurations

### ISSUE THREAD

**Issue by rukaury** [neo4j-contrib/neo4j-helm#236]
Hi,

I have followed the steps on how to setup a standalone neo4j instance in a kubernetes cluster from this documentation: https://neo4j.com/docs/operations-manual/current/kubernetes/quickstart-standalone/ 

Everything went well, however i would like to use the apoc import and export features from neo4j but when i try to do so in neo4j browser, it says export or import are not enabled. However, when i exec into the pod, i can see the configurations in the neo4j.conf file.

Here is my helm config yaml file content:

neo4j:
  resources:
    cpu: "1"
    memory: "500Mi"
  password: "*********************************"
  edition: "enterprise"
  acceptLicenseAgreement: "yes"

volumes:
  data:
    mode: "volume"
    volume:
      azureDisk:
        diskName: "myDiskName"
        diskURI: "myDiskURI"
        kind: Managed
        
  import:
    mode: "volume"
    volume:
      azureFile:
        secretName: mySecretName
        shareName: myShareName
        readOnly: false
        
config:
  dbms.directories.plugins: "/var/lib/neo4j/labs"
  dbms.security.procedures.unrestricted: "apoc.*"
  
env: {
  NEO4J_apoc_import_file_enabled: "true", 
  NEO4J_apoc_export_file_enabled: "true",
  NEO4J_apoc_import_file_use__neo4j__config: "true",
  NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
}

Can someone help me achieve what i am looking for?

**Comment by moxious** [comment]
Hi @rukaury this can depend on which version of APOC you're using, the docs you're following may be referring to an older version of APOC which placed its config in neo4j.conf.

More recent versions of APOC expect a separate file in conf/apoc.conf.  To do this, rather than using env vars what you would probably do is create a configmap mounted as a file to that location to configure APOC.  You could do this once, and then have the file mount go to all of your containers.

For APOC config, check here: https://neo4j.com/labs/apoc/4.3/config/

Also, please take note that this repo is deprecated, see this message for next steps: https://github.com/neo4j-contrib/neo4j-helm#deprecated

**Comment by rukaury** [comment]
Thank you very much for this clear and precise answer, i will definitely take a look and comment the solution that i found.

**Comment by rukaury** [comment]
I got it to work, i added the config map below and now it can read the configurations:

apiVersion: v1
kind: ConfigMap
metadata:
  name: "my-neo4j-release-apoc-config"
  namespace: "default"
data:
  apoc.conf: |
    apoc.export.file.enabled=true
    apoc.import.file.enabled=true
    apoc.import.file.use_neo4j_config=true


Thanks again for your guidance.

**Comment by org-ci-cd** [comment]
Same issue, it feels like the helm chart doesn't have an easy way to add an additional volume mount ? @AdrienLemaire  did you find how ?
