### ISSUE TITLE
Is it possible to add the useGDS plugins configuration for values.yaml?

### ISSUE THREAD

**Issue by bugzyz** [neo4j-contrib/neo4j-helm#49]
Hi! 
We are using the apoc and gds plugins on the cluster created by your perfect helm chart!
Is it possible to add the useGDS configuration just like the useAPOC configuration in your future version?

**Comment by moxious** [comment]
Probably yes.  I haven't wanted to do this recently because GDS publishing / availability for the docker platform is very new (like - what last week?).  There are other plugins as well to support.  An idea has been that we might expand this to "official" plugins by changing the format a bit.  Instead of useAPOC true, useGDS true, it might be something more like this:

```
officialPlugins:
    apoc: true
    gds: true
    somethingElse: true
```

(APOC=true would still be the only default -- and this would only ever work with neo4j labs stuff -- the use of initContainers I think will always be required for custom plugins or non-official code)

Thoughts?

**Comment by moxious** [comment]
See this PR here:  https://github.com/neo4j-contrib/neo4j-helm/pull/51

The docker container already allows us to specify an array of plugins from a valid set of names (reference list in the PR).  This seems to me to be the best way to do it, and I've included a sample deployment that uses both APOC + GDS in the same container.

**Comment by bugzyz** [comment]
Thanks @moxious! 
It works fine and now it's very convenient for us to enable both the apoc and gds plugins in our neo4j cluster!
:)
