### ISSUE TITLE
Backup methods

### ISSUE THREAD

**Issue by srfaytkn** [neo4j-contrib/neo4j-helm#56]
Can velero(pvc) be used instead of neo4j backup? Does it pose any risk of data corruption?

**Comment by moxious** [comment]
I'm not sure I understand the question.   It is possible to use neo4j-backup to persist a backup set on just a regular PVC though, yes.  The reason I'd recommend using cloud storage and not a PVC is because you can set policies with other services, and also cloud storage can be multi-region replicated.  When you use a PVC, chances are good your backup is in the same geographic area as your cluster, which can be bad for availability reasons.

**Comment by srfaytkn** [comment]
thank you
