### ISSUE TITLE
Enable users to set static NodePort

### ISSUE THREAD

**Issue by c4tz** [neo4j-contrib/neo4j-helm#58]
Hey there,

thank you for this terrific chart! I hope you can help me with this;

I just wanted to deploy a standalone Neo4j instance with it and stumbled upon the fact that one can set `core.service.type` to `NodePort`, but there is no option to set a specific port when doing so.

I'd create a PR, but I'm not quite sure how to handle the multiple ports declared in https://github.com/neo4j-contrib/neo4j-helm/blob/master/templates/core-dns.yaml yet.

An example for a parameterized NodePort can be found in the Sentry Helm chart: https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/service-sentry.yaml#L25

**Comment by moxious** [comment]
Can you back up and first detail what you're trying to do?  I'm also not sure which port to expose because it depends.

I don't typically use NodePorts because they map to the actual worker nodes IP addresses, right?  So then to avoid conflicts, you would either have to set up a port spreading arrangement (i.e. bolt on port 7687 on machine 0, 7688 on machine 1, and so on) -- or you would have to pair NodePort rules together with anti-affinity rules of some sort to guarantee they'd be separate.

**Comment by c4tz** [comment]
Thank you for the reply.

In our infrastructure, each service uses a static NodePort, because (I think, had to ask the SRE team to clarify) that is whats entered in our (custom) load balancer in order to make the service available under an (internal) URL.

When let kubectl describe my neo4j standalone instance with type `NodePort` I see something like this:

```
IP:                       10.10.1.123
Port:                     http  7474/TCP
TargetPort:               7474/TCP
NodePort:                 http  12345/TCP
Endpoints:                10.10.10.72:7474
Port:                     bolt  7687/TCP
TargetPort:               7687/TCP
NodePort:                 bolt  12346/TCP
Endpoints:                10.10.10.72:7687
Port:                     https  7473/TCP
TargetPort:               7473/TCP
NodePort:                 https  12347/TCP
Endpoints:                10.10.10.72:7473
Port:                     backup  6362/TCP
TargetPort:               6362/TCP
NodePort:                 backup  12348/TCP
Endpoints:                10.10.10.72:6362
```

So there already is a separate NodePort for each open Port. The only problem for me is, that they are currently dynamically assigned by kubernetes and if I restart the Node, they might have another value. To encounter this, we set them statically.

So, for example, my neo4j instance could be running at `neo4j.example.com`. To be able to accomplish this, I'd set the service type to NodePort (with a static Port) and let `neo4j.example.com` point to `10.10.1.123:12345`. Now, as I said, I have not come to a case where a service needed multiple ports being mapped to NodePorts. But I could imagine this would work with subdomains, like mapping `bolt.neo4j.example.com` to `10.10.1.123:12346`, e.g.

One solution to this would be to be able to set each NodePort-Port combination explicitly in the `values.yml`, which is then mapped in `core-dns.yml` as I linked above.

But maybe this would be overkill and there is an easier solution?

**Comment by moxious** [comment]
@c4tz sorry for the late response, but there's a lot going on here.  In no particular order:

- the core-dns.yaml file is intended as a single point of entry service for clients to point to.  You can expose it to the outside world for a single instance, but for a cluster even getting this perfect wouldn't be enough.  Because of the way the smart client protocol works in routing queries for Neo4j, you'd still have to expose each of the underlying pods individually.  Are you right now working with single instances, would you need clusters later?  Because this is an important point to consider before even starting.

- NodePorts aren't really recommended for production at all.  [You can read more here](https://www.ovh.com/blog/getting-external-traffic-into-kubernetes-clusterip-nodeport-loadbalancer-and-ingress/) but among other problems, no matter which node IP your traffic gets exposed on, you have a dependency on the underlying worker VM being up.  So even if your pod is deployed to a different node, it could become unavailable if the nodeport isn't available.

- I see your problem about the dynamic allocation of NodePorts.  This was one reason why in the repo there are instructions for externally exposing Neo4j.  This is the approach that I would recommend, because it gives you a single stable IP address of your choosing, that you can configure ahead of time, without dependency on the way Kubernetes selects things.  Have you had a look at this approach, and if it's not suitable for you, why not?

- I'm personally not aware of a way that you can do the static assignment with NodePort, but that's maybe just a limitation of my knowledge.  Your subdomain idea seems to me like it could work, but it does seem complex and I sorta think the external exposure instructions in the repo are easier to understand and straightforward.

**Comment by c4tz** [comment]
Hey @moxious I'm terribly sorry for letting you wait for so long. I spoke to someone from our SRE team (after he came back from vacation) and was told that because of how the custom loadbalancer works, we'd need  a NodePort in order to create a public URL for a service.

But after reading the article you linked I realized I could also just use `kubectl port-forward` in order to achieve what I wanted ( to be able to test queries directly against the staging neo4j db)!

So for now, I think I'll just stick to using ClusterIPs. Thank you for you time and detailed explanation. :)
