### ISSUE TITLE
Issue with svc.cluster.local

### ISSUE THREAD

**Issue by ShepardZhao** [neo4j-contrib/neo4j-helm#67]
Hello there, 

I have a question on this postfix svc.cluster.local. can we remove this only keep $workloadName.$namespace ? 

I am unable to remove svc.cluster.local somehow even I setup the NEO4J_causal__clustering_initial__discovery__members and 
__clustering_discovery__advertised__address to NEO4J_causal__clustering_discovery__advertised__address:-$HOST:5000

The $HOST will be export HOST=${HOST:-$(hostname -f)}; echo $HOST will be c-neo4j-core-0.c-neo4j.oss-prod-ns.svc.xxx.xxx.io for example 

Thanks for advise~

**Comment by moxious** [comment]
`cluster.local` is chosen by kubernetes itself and not by the helm chart.  To do what you're trying to do, you can change the default `clusterDomain` value (see values.yaml) -- but in order for Kubernetes to support whatever you'd change it to, you need to customize your kubernetes DNS.   https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/

So it's possible, but not directly supported by this chart.

**Comment by ShepardZhao** [comment]
@moxious  thanks for feedback. I just take look the clusterDomain and change it to clusterDomain: 57.xxx.io. However, it is still not working

**Comment by moxious** [comment]
@ShepardZhao did you do the k8s cluster DNS customization behind the link that I specified?  Changing the clusterDomain in the helm chart alone cannot work, because if the kubernetes system itself doesn't recognize that domain name, services cannot simply choose their own and be recognized.  

If you did the customization, please specify how you did it, and what the error was, to be more specific about what it isn't working means.

**Comment by phoerious** [comment]
This is a bug in the template for the stateful set: https://github.com/neo4j-contrib/neo4j-helm/blob/0d70fcc2bb6090563e643abe0250c406e2118636/templates/core-statefulset.yaml#L83

cluster.local is hard-coded in the init script and should be replaced with `{{ .Values.clusterDomain }}``.

**Comment by phoerious** [comment]
Fixing the Helm chart alone isn't enough it seems. This problem goes much deeper: https://github.com/neo4j/neo4j/issues/12139

**Comment by moxious** [comment]
Hard-coded cluster.local is a legit issue; will open a PR shortly addressing that.

**Comment by moxious** [comment]
@phoerious as for the specific claim that the product internally requires the cluster.local domain suffix, I'm going to take that up with some clustering folks that I know and see what they think.   I will ensure that you don't need to hotfix this in the helm chart itself, but that separate issue requires separate follow-up.

**Comment by moxious** [comment]
@phoerious got an update from our cluster team about the internal neo4j hard-coded domain bug.  It's already been fixed internally, but the resulting fix won't see the light until release of 4.2.   I'm going to leave this issue open although there's no further action necessary on the helm side.   When 4.2 is out I'll cut a release of neo4j-helm for that, and with any release of neo4j-helm which uses neo4j 4.2, this bug is fixed.

**Comment by moxious** [comment]
UPDATE:  Referring to and tying this issue to another thread going on here: https://github.com/neo4j/neo4j/issues/12139

Current status remains the same.  Here's what our forward plan on this one is:

* While it is right now fixed in the helm chart, there's still a hard-coded cluster domain in the actual Neo4j product, and so this issue can't be fixed/closed by this repo
* When Neo4j 4.2 arrives (which should be under one month from now) the fix should arrive in the Neo4j product.
* At that point, I will issue a release of neo4j-helm against Neo4j 4.2.0, and that will close this issue
* A note will be added to the documentation that for versions < 4.2 this is still going to be present; the fix is not being backported.

**Comment by ShepardZhao** [comment]
Thanks guys. I have seen the version 4.2 image has been released. Does this issue have been resolved?

**Comment by ShepardZhao** [comment]
Hi Guys, I Just figured out params from inside of 4.2 version 
    
**NEO4J_SETTINGS[NEO4J_causal__clustering_kubernetes_cluster__domain]="xxxx.io"**

this is what param that needs to add

**Comment by moxious** [comment]
@ShepardZhao yes, that is correct.  As of 4.2.0 that config key is available, and it's the right one to use in this context.   I still haven't issued a release based on 4.2.0 yet but when I do this will be closed.

**Comment by ShepardZhao** [comment]
thanks @moxious

**Comment by moxious** [comment]
Release was issued yesterday afternoon (4.2.0-1) and accordingly this ticket is now closed.
